name: API Tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Run the tests
      - name: Run API Tests
        run: npm run test
